In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [151]:
train_df = pd.read_csv("task2/data/train.csv")

test_df = pd.read_csv("task2/data/test.csv")

In [132]:
test_df.isnull().sum()

season        0
price_AUS    33
price_CZE    25
price_GER    31
price_ESP    39
price_FRA    25
price_UK     24
price_ITA    30
price_POL    35
price_SVK    34
dtype: int64

In [133]:
train_df.isnull().sum()

season         0
price_AUS    262
price_CHF    269
price_CZE    268
price_GER    269
price_ESP    269
price_FRA    264
price_UK     287
price_ITA    266
price_POL    265
price_SVK    281
dtype: int64

In [134]:
test_df

,season,price_AUS,price_CZE,price_GER,price_ESP,price_FRA,price_UK,price_ITA,price_POL,price_SVK
0,spring,NaN,0.472985,0.707957,NaN,-1.136441,-0.596703,NaN,3.298693,1.921886
1,summer,-1.184837,0.358019,NaN,-3.199028,-1.069695,NaN,-1.420091,3.238307,NaN
2,autumn,-1.116459,NaN,0.780460,-3.338948,-1.053149,-0.586339,NaN,3.207398,2.020570
3,winter,NaN,0.353066,0.833429,NaN,-1.322626,-0.628873,-1.304240,3.159858,NaN
4,spring,NaN,0.269644,NaN,-3.245495,-1.362051,-0.717914,-1.341538,3.205007,NaN
...,...,...,...,...,...,...,...,...,...,...
95,winter,-2.030894,NaN,-1.332104,-3.838154,NaN,-2.319565,NaN,-2.134084,-2.880557
96,spring,-1.817763,NaN,NaN,-3.995247,-3.760752,NaN,-3.903510,-2.269992,-3.007311
97,summer,NaN,NaN,-1.140538,-4.084448,-3.968988,-2.555133,-4.058773,-2.146487,-2.816678
98,autumn,NaN,-1.029762,NaN,-4.216490,-3.705548,-2.487751,-3.745480,NaN,-2.849707
99,winter,-1.472852,-0.935032,NaN,-4.463277,-3.488559,NaN,-3.534069,-1.836267,NaN

In [135]:
train_df

,season,price_AUS,price_CHF,price_CZE,price_GER,price_ESP,price_FRA,price_UK,price_ITA,price_POL,price_SVK
0,spring,NaN,9.644028,-1.686248,-1.748076,-3.666005,NaN,-1.822720,-3.931031,NaN,-3.238197
1,summer,NaN,7.246061,-2.132377,-2.054363,-3.295697,-4.104759,-1.826021,NaN,NaN,-3.212894
2,autumn,-2.101937,7.620085,-1.910282,NaN,-3.388777,NaN,-2.034409,-4.073850,NaN,-3.114061
3,winter,-2.098475,8.411894,-1.903834,NaN,-3.588235,NaN,-2.214720,-4.018620,-2.330803,NaN
4,spring,-1.969687,8.926884,-1.697257,-1.331049,NaN,-3.911096,-2.388092,-4.093946,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
895,winter,-1.044730,NaN,0.190134,0.253153,-3.443941,-1.967611,NaN,-1.838593,3.235645,NaN
896,spring,-1.061639,-1.734754,0.281646,NaN,-3.466753,-1.929701,NaN,-1.508756,3.187263,NaN
897,summer,-0.971157,NaN,0.245279,0.558474,NaN,NaN,-0.843659,-1.499361,3.110638,2.230253
898,autumn,NaN,NaN,0.299911,0.788152,-3.339650,NaN,-0.865169,-1.547716,3.105417,1.989140
899,winter,-1.058343,NaN,0.231835,0.800460,-3.377680,-1.200493,NaN,NaN,3.272816,2.080667

In [136]:
train_df_new = train_df.dropna(subset='price_CHF')
train_df_new

,season,price_AUS,price_CHF,price_CZE,price_GER,price_ESP,price_FRA,price_UK,price_ITA,price_POL,price_SVK
0,spring,NaN,9.644028,-1.686248,-1.748076,-3.666005,NaN,-1.822720,-3.931031,NaN,-3.238197
1,summer,NaN,7.246061,-2.132377,-2.054363,-3.295697,-4.104759,-1.826021,NaN,NaN,-3.212894
2,autumn,-2.101937,7.620085,-1.910282,NaN,-3.388777,NaN,-2.034409,-4.073850,NaN,-3.114061
3,winter,-2.098475,8.411894,-1.903834,NaN,-3.588235,NaN,-2.214720,-4.018620,-2.330803,NaN
4,spring,-1.969687,8.926884,-1.697257,-1.331049,NaN,-3.911096,-2.388092,-4.093946,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
889,summer,NaN,3.237347,0.235917,-0.306331,NaN,-2.735177,-1.839910,-2.378179,2.535228,NaN
890,autumn,-1.079859,2.679221,NaN,-0.226806,NaN,NaN,-1.807515,-2.223057,2.555153,2.189913
891,winter,-0.961371,3.633928,0.352449,NaN,-3.488688,NaN,-1.568924,NaN,2.706716,2.520366
894,autumn,-1.186919,-0.303802,NaN,0.236214,-3.333672,-2.262145,-1.246151,-1.801203,NaN,NaN
896,spring,-1.061639,-1.734754,0.281646,NaN,-3.466753,-1.929701,NaN,-1.508756,3.187263,NaN

In [137]:
test_df_new = test_df

In [138]:
le = LabelEncoder()
label = le.fit_transform(train_df_new['season'])
label_test = le.fit_transform(test_df_new['season'])

train_df_new['season'] = label
test_df_new['season'] = label_test

C:\Users\timfl\AppData\Local\Temp\ipykernel_9696\2216429546.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_new['season'] = label

In [139]:
train_df_new

,season,price_AUS,price_CHF,price_CZE,price_GER,price_ESP,price_FRA,price_UK,price_ITA,price_POL,price_SVK
0,1,NaN,9.644028,-1.686248,-1.748076,-3.666005,NaN,-1.822720,-3.931031,NaN,-3.238197
1,2,NaN,7.246061,-2.132377,-2.054363,-3.295697,-4.104759,-1.826021,NaN,NaN,-3.212894
2,0,-2.101937,7.620085,-1.910282,NaN,-3.388777,NaN,-2.034409,-4.073850,NaN,-3.114061
3,3,-2.098475,8.411894,-1.903834,NaN,-3.588235,NaN,-2.214720,-4.018620,-2.330803,NaN
4,1,-1.969687,8.926884,-1.697257,-1.331049,NaN,-3.911096,-2.388092,-4.093946,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
889,2,NaN,3.237347,0.235917,-0.306331,NaN,-2.735177,-1.839910,-2.378179,2.535228,NaN
890,0,-1.079859,2.679221,NaN,-0.226806,NaN,NaN,-1.807515,-2.223057,2.555153,2.189913
891,3,-0.961371,3.633928,0.352449,NaN,-3.488688,NaN,-1.568924,NaN,2.706716,2.520366
894,0,-1.186919,-0.303802,NaN,0.236214,-3.333672,-2.262145,-1.246151,-1.801203,NaN,NaN
896,1,-1.061639,-1.734754,0.281646,NaN,-3.466753,-1.929701,NaN,-1.508756,3.187263,NaN

In [140]:
test_df_new

,season,price_AUS,price_CZE,price_GER,price_ESP,price_FRA,price_UK,price_ITA,price_POL,price_SVK
0,1,NaN,0.472985,0.707957,NaN,-1.136441,-0.596703,NaN,3.298693,1.921886
1,2,-1.184837,0.358019,NaN,-3.199028,-1.069695,NaN,-1.420091,3.238307,NaN
2,0,-1.116459,NaN,0.780460,-3.338948,-1.053149,-0.586339,NaN,3.207398,2.020570
3,3,NaN,0.353066,0.833429,NaN,-1.322626,-0.628873,-1.304240,3.159858,NaN
4,1,NaN,0.269644,NaN,-3.245495,-1.362051,-0.717914,-1.341538,3.205007,NaN
...,...,...,...,...,...,...,...,...,...,...
95,3,-2.030894,NaN,-1.332104,-3.838154,NaN,-2.319565,NaN,-2.134084,-2.880557
96,1,-1.817763,NaN,NaN,-3.995247,-3.760752,NaN,-3.903510,-2.269992,-3.007311
97,2,NaN,NaN,-1.140538,-4.084448,-3.968988,-2.555133,-4.058773,-2.146487,-2.816678
98,0,NaN,-1.029762,NaN,-4.216490,-3.705548,-2.487751,-3.745480,NaN,-2.849707
99,3,-1.472852,-0.935032,NaN,-4.463277,-3.488559,NaN,-3.534069,-1.836267,NaN

In [141]:
train_df

,season,price_AUS,price_CHF,price_CZE,price_GER,price_ESP,price_FRA,price_UK,price_ITA,price_POL,price_SVK
0,spring,NaN,9.644028,-1.686248,-1.748076,-3.666005,NaN,-1.822720,-3.931031,NaN,-3.238197
1,summer,NaN,7.246061,-2.132377,-2.054363,-3.295697,-4.104759,-1.826021,NaN,NaN,-3.212894
2,autumn,-2.101937,7.620085,-1.910282,NaN,-3.388777,NaN,-2.034409,-4.073850,NaN,-3.114061
3,winter,-2.098475,8.411894,-1.903834,NaN,-3.588235,NaN,-2.214720,-4.018620,-2.330803,NaN
4,spring,-1.969687,8.926884,-1.697257,-1.331049,NaN,-3.911096,-2.388092,-4.093946,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
895,winter,-1.044730,NaN,0.190134,0.253153,-3.443941,-1.967611,NaN,-1.838593,3.235645,NaN
896,spring,-1.061639,-1.734754,0.281646,NaN,-3.466753,-1.929701,NaN,-1.508756,3.187263,NaN
897,summer,-0.971157,NaN,0.245279,0.558474,NaN,NaN,-0.843659,-1.499361,3.110638,2.230253
898,autumn,NaN,NaN,0.299911,0.788152,-3.339650,NaN,-0.865169,-1.547716,3.105417,1.989140
899,winter,-1.058343,NaN,0.231835,0.800460,-3.377680,-1.200493,NaN,NaN,3.272816,2.080667

In [142]:
train_df_new.groupby(['season'])['price_AUS'].median().round(2)

season
0   -0.78
1   -0.52
2   -0.69
3   -0.48
Name: price_AUS, dtype: float64

In [143]:
train_df_new.columns[1]

'price_AUS'

In [144]:
for item in train_df_new.columns:
    train_df_new[item] = train_df_new.groupby('season')[item].transform(lambda x: x.fillna(x.median()))
for item in test_df_new.columns:
    test_df_new[item] = test_df_new.groupby('season')[item].transform(lambda x: x.fillna(x.median()))

C:\Users\timfl\AppData\Local\Temp\ipykernel_9696\1614013212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_new[item] = train_df_new.groupby('season')[item].transform(lambda x: x.fillna(x.median()))
C:\Users\timfl\AppData\Local\Temp\ipykernel_9696\1614013212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_new[item] = train_df_new.groupby('season')[item].transform(lambda x: x.fillna(x.median()))
C:\Users\timfl\AppData\Local\Temp\ipykernel_9696\1614013212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_new[item] = train_df_new.groupby('season')[item].transform(lambda x: x.fillna(x.median()))
C:\Users\timfl\AppData\Local\Temp\ipykernel_9696\1614013212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_new[item] = train_df_new.groupby('season')[item].transform(lambda x: x.fillna(x.median()))
C:\Users\timfl\AppData\Local\Temp\ipykernel_9696\1614013212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_new[item] = train_df_new.groupby('season')[item].transform(lambda x: x.fillna(x.median()))
C:\Users\timfl\AppData\Local\Temp\ipykernel_9696\1614013212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_new[item] = train_df_new.groupby('season')[item].transform(lambda x: x.fillna(x.median()))
C:\Users\timfl\AppData\Local\Temp\ipykernel_9696\1614013212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_new[item] = train_df_new.groupby('season')[item].transform(lambda x: x.fillna(x.median()))
C:\Users\timfl\AppData\Local\Temp\ipykernel_9696\1614013212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_new[item] = train_df_new.groupby('season')[item].transform(lambda x: x.fillna(x.median()))
C:\Users\timfl\AppData\Local\Temp\ipykernel_9696\1614013212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_new[item] = train_df_new.groupby('season')[item].transform(lambda x: x.fillna(x.median()))
C:\Users\timfl\AppData\Local\Temp\ipykernel_9696\1614013212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_new[item] = train_df_new.groupby('season')[item].transform(lambda x: x.fillna(x.median()))
C:\Users\timfl\AppData\Local\Temp\ipykernel_9696\1614013212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_new[item] = train_df_new.groupby('season')[item].transform(lambda x: x.fillna(x.median()))

In [145]:
train_df

,season,price_AUS,price_CHF,price_CZE,price_GER,price_ESP,price_FRA,price_UK,price_ITA,price_POL,price_SVK
0,spring,NaN,9.644028,-1.686248,-1.748076,-3.666005,NaN,-1.822720,-3.931031,NaN,-3.238197
1,summer,NaN,7.246061,-2.132377,-2.054363,-3.295697,-4.104759,-1.826021,NaN,NaN,-3.212894
2,autumn,-2.101937,7.620085,-1.910282,NaN,-3.388777,NaN,-2.034409,-4.073850,NaN,-3.114061
3,winter,-2.098475,8.411894,-1.903834,NaN,-3.588235,NaN,-2.214720,-4.018620,-2.330803,NaN
4,spring,-1.969687,8.926884,-1.697257,-1.331049,NaN,-3.911096,-2.388092,-4.093946,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
895,winter,-1.044730,NaN,0.190134,0.253153,-3.443941,-1.967611,NaN,-1.838593,3.235645,NaN
896,spring,-1.061639,-1.734754,0.281646,NaN,-3.466753,-1.929701,NaN,-1.508756,3.187263,NaN
897,summer,-0.971157,NaN,0.245279,0.558474,NaN,NaN,-0.843659,-1.499361,3.110638,2.230253
898,autumn,NaN,NaN,0.299911,0.788152,-3.339650,NaN,-0.865169,-1.547716,3.105417,1.989140
899,winter,-1.058343,NaN,0.231835,0.800460,-3.377680,-1.200493,NaN,NaN,3.272816,2.080667

In [153]:
train_df_new

,season,price_AUS,price_CHF,price_CZE,price_GER,price_ESP,price_FRA,price_UK,price_ITA,price_POL,price_SVK
0,1,-0.519757,9.644028,-1.686248,-1.748076,-3.666005,-3.176436,-1.822720,-3.931031,-0.796854,-3.238197
1,2,-0.689416,7.246061,-2.132377,-2.054363,-3.295697,-4.104759,-1.826021,-3.143001,-0.818474,-3.212894
2,0,-2.101937,7.620085,-1.910282,-0.379059,-3.388777,-3.396470,-2.034409,-4.073850,-0.568260,-3.114061
3,3,-2.098475,8.411894,-1.903834,-0.146333,-3.588235,-3.286866,-2.214720,-4.018620,-2.330803,-0.137858
4,1,-1.969687,8.926884,-1.697257,-1.331049,-4.393997,-3.911096,-2.388092,-4.093946,-0.796854,-0.631569
...,...,...,...,...,...,...,...,...,...,...,...
889,2,-0.689416,3.237347,0.235917,-0.306331,-4.237861,-2.735177,-1.839910,-2.378179,2.535228,-1.428323
890,0,-1.079859,2.679221,-0.113687,-0.226806,-4.425276,-3.396470,-1.807515,-2.223057,2.555153,2.189913
891,3,-0.961371,3.633928,0.352449,-0.146333,-3.488688,-3.286866,-1.568924,-2.937887,2.706716,2.520366
894,0,-1.186919,-0.303802,-0.113687,0.236214,-3.333672,-2.262145,-1.246151,-1.801203,-0.568260,-1.000371
896,1,-1.061639,-1.734754,0.281646,-0.230815,-3.466753,-1.929701,-1.897642,-1.508756,3.187263,-0.631569

In [146]:
test_df_new

,season,price_AUS,price_CZE,price_GER,price_ESP,price_FRA,price_UK,price_ITA,price_POL,price_SVK
0,1,-1.428443,0.472985,0.707957,-3.609895,-1.136441,-0.596703,-3.509396,3.298693,1.921886
1,2,-1.184837,0.358019,-1.344293,-3.199028,-1.069695,-2.103320,-1.420091,3.238307,-2.868300
2,0,-1.116459,-1.418303,0.780460,-3.338948,-1.053149,-0.586339,-3.626742,3.207398,2.020570
3,3,-1.394824,0.353066,0.833429,-3.931837,-1.322626,-0.628873,-1.304240,3.159858,-2.643545
4,1,-1.428443,0.269644,-1.032372,-3.245495,-1.362051,-0.717914,-1.341538,3.205007,-2.844691
...,...,...,...,...,...,...,...,...,...,...
95,3,-2.030894,-1.217764,-1.332104,-3.838154,-3.777239,-2.319565,-3.391026,-2.134084,-2.880557
96,1,-1.817763,-1.047298,-1.032372,-3.995247,-3.760752,-2.137154,-3.903510,-2.269992,-3.007311
97,2,-1.449465,-1.493495,-1.140538,-4.084448,-3.968988,-2.555133,-4.058773,-2.146487,-2.816678
98,0,-1.430368,-1.029762,-0.854572,-4.216490,-3.705548,-2.487751,-3.745480,-2.358626,-2.849707
99,3,-1.472852,-0.935032,-1.167556,-4.463277,-3.488559,-2.159804,-3.534069,-1.836267,-2.643545

In [152]:
test_df

,season,price_AUS,price_CZE,price_GER,price_ESP,price_FRA,price_UK,price_ITA,price_POL,price_SVK
0,spring,NaN,0.472985,0.707957,NaN,-1.136441,-0.596703,NaN,3.298693,1.921886
1,summer,-1.184837,0.358019,NaN,-3.199028,-1.069695,NaN,-1.420091,3.238307,NaN
2,autumn,-1.116459,NaN,0.780460,-3.338948,-1.053149,-0.586339,NaN,3.207398,2.020570
3,winter,NaN,0.353066,0.833429,NaN,-1.322626,-0.628873,-1.304240,3.159858,NaN
4,spring,NaN,0.269644,NaN,-3.245495,-1.362051,-0.717914,-1.341538,3.205007,NaN
...,...,...,...,...,...,...,...,...,...,...
95,winter,-2.030894,NaN,-1.332104,-3.838154,NaN,-2.319565,NaN,-2.134084,-2.880557
96,spring,-1.817763,NaN,NaN,-3.995247,-3.760752,NaN,-3.903510,-2.269992,-3.007311
97,summer,NaN,NaN,-1.140538,-4.084448,-3.968988,-2.555133,-4.058773,-2.146487,-2.816678
98,autumn,NaN,-1.029762,NaN,-4.216490,-3.705548,-2.487751,-3.745480,NaN,-2.849707
99,winter,-1.472852,-0.935032,NaN,-4.463277,-3.488559,NaN,-3.534069,-1.836267,NaN

In [154]:
X_train = train_df_new.drop(['price_CHF'], axis = 1)
y_train = train_df_new['price_CHF']
X_test = test_df_new

In [191]:
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import (RBF, Matern, RationalQuadratic, ExpSineSquared, DotProduct, ConstantKernel)
gpr = GaussianProcessRegressor(kernel=DotProduct())
gpr.fit(X_train, y_train)

GaussianProcessRegressor(kernel=DotProduct(sigma_0=1))

In [163]:
pred = gpr.predict(X_test)

In [166]:
kernel = gpr.kernel_

In [167]:
kernel

DotProduct(sigma_0=0.0155)

In [215]:
from sklearn.model_selection import GridSearchCV

models = GaussianProcessRegressor()
                
param_grid = [{
    "alpha":  [1e-2, 1e-3],
    "kernel": [RBF(l) for l in np.logspace(-1, 1, 2)]
}, {
    "alpha":  [1e-2, 1e-3],
    "kernel": [DotProduct(sigma_0) for sigma_0 in np.logspace(-1, 1, 2)]
}, {
    "alpha":  [1e-2, 1e-3],
    "kernel": [Matern(length_scale=1.0, nu=1.5)]
    
}]

In [216]:
clf = GridSearchCV(models, param_grid)
clf.fit(X_train, y_train)

C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\kernels.py:430: ConvergenceWarning: The optimal value found for dimension 0 of parameter sigma_0 is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\_gpr.py:629: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)
C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\kernels.py:430: ConvergenceWarning: The optimal value found for dimension 0 of parameter sigma_0 is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\timfl\anaconda3\envs\IML\lib\site-packages\sklearn\gaussian_process\kernels.py:430: ConvergenceWarning: The optimal value found for dimension 0 of parameter sigma_0 is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

GridSearchCV(estimator=GaussianProcessRegressor(),
             param_grid=[{'alpha': [0.01, 0.001],
                          'kernel': [RBF(length_scale=0.1),
                                     RBF(length_scale=10)]},
                         {'alpha': [0.01, 0.001],
                          'kernel': [DotProduct(sigma_0=0.1),
                                     DotProduct(sigma_0=10)]},
                         {'alpha': [0.01, 0.001],
                          'kernel': [Matern(length_scale=1, nu=1.5)]}])

In [217]:
print(clf.best_params_)

{'alpha': 0.01, 'kernel': Matern(length_scale=1, nu=1.5)}